apply_patches_db: False
db_homes_config:
  19300-base:
    home: db1-base
    version: 19.3.0.0
    edition: EE
  # 12201-base:
  #   home: db1-base
  #   version: 12.2.0.1
  #   edition: EE
  # 12201-latest:
  #   home: db1-latest
  #   version: 12.2.0.1
  #   edition: EE
  #   opatch_minversion: 12.2.0.1.12
  #   opatchauto:
  #       - patchid: 28183653
  #         patchversion: 12.2.0.1.180717
  #         state: present
  #         subpatches:
  #             - 28163133
  #             - 28163190
  #   opatch: []

db_homes_installed:
     - home: 18300-base
       apply_patches: False
       state: present
     # - home: 12201-base
     #   apply_patches: False
     #   state: present
     # - home: 12201-latest
     #   apply_patches: True
     #   state: absent
