- name: Customize database
  hosts: "{{ hostgroup }}"
  sudo: yes
  roles:
    - oradb-manage-pdb
    - oradb-manage-tablespace
    - oradb-manage-parameters
    - oradb-manage-redo
    - oradb-manage-roles
    - oradb-manage-users
    - oradb-manage-grants
    - oradb-manage-services
