---

  - name: Delete database(s)
    shell: "{{ oracle_home_db }}/bin/dbca -deleteDatabase -sourceDB {{ item.oracle_db_name }} -sysDBAUserName sys -sysDBAPassword {{dbpasswords[item.oracle_db_name]['sys']}} -silent"
    with_items: "{{oracle_databases}}"
    run_once: "{{ configure_cluster}}"
    when: item.state |upper == 'ABSENT'
    tags:
      - oradbdelete
    register: oradbdelete

  - debug: var=oraddelete.stdout_lines
    with_items: oradbdelete.results
    tags:
     - oradbdelete
