oracle_databases:                                               # Dictionary describing the databases to be installed
      - home: 19300-base                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
        oracle_db_name: orclcdb                                 # Database name
        oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
        is_container: True                                # (true/false) Is the database a container database 
        oracle_version_db: 19.3.0.0
        storage_type: FS                                     # Database storage to be used. ASM or FS.
        oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
        oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
        redolog_size: 75M
        redolog_groups: 3
        datafile_dest: /u02/oradata
        recoveryfile_dest: /u02/fra
        listener_name: LISTENER                              # This home will have a listener configured
        listener_port: 1521
        archivelog: False
        flashback: False
        force_logging: False
        state: present
        # tablespaces:
        #      - { name: users, size: 10M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
        init_parameters:
             - {name: db_create_file_dest, value: '/u02/oradata', scope: both, state: present}
             - {name: db_create_online_log_dest_1, value: '/u02/fra', scope: both, state: present}
             - {name: db_recovery_file_dest, value: '/u02/fra', scope: both, state: present}
             - {name: db_recovery_file_dest_size, value: 20G, scope: both, state: present}
        # services:
        #      - { name: service2,  state: started }
        # users:
        #   - schema: c##dba
        #     container: all
        #     grants:
        #          - dba
        #     state: present
      # - home: db1                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
      #   oracle_version_db: 12.1.0.2                         # Oracle versiono (12.2.0.1,12.1.0.2,12.1.0.1,11.2.0.4,11.2.0.3)
      #   oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
      #   oracle_db_name: db121                                 # Database name
      #   oracle_db_passwd: Oracle123                          # Passwords (sys/system/dbsnm etc)
      #   oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
      #   is_container: True                                # (true/false) Is the database a container database
      #   storage_type: FS                                     # Database storage to be used. ASM or FS.
      #   oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
      #   oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
      #   redolog_size_in_mb: 100
      #   datafile_dest: /u02/oradata
      #   recoveryfile_dest: /u02/fra
      #   state: present
      #   init_parameters:
      #        - {name: db_create_file_dest, value: '/u02/oradata', scope: both, state: present}
      #        - {name: db_recovery_file_dest, value: '/u02/fra', scope: both, state: present}
      #        - {name: db_recovery_file_dest_size, value: 20G, scope: both, state: present}
      #   services:
      #        - { name: service121,  state: started }
      #   users:
      #     - schema: c##dba
      #       container: all
      #       grants:
      #            - dba
      #       state: present
      # - home: db1                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
      #   oracle_version_db: 11.2.0.4                         # Oracle versiono (12.2.0.1,12.1.0.2,12.1.0.1,11.2.0.4,11.2.0.3)
      #   oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
      #   oracle_db_name: db112                                 # Database name
      #   oracle_db_passwd: Oracle123                          # Passwords (sys/system/dbsnm etc)
      #   oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
      #   is_container: True                                # (true/false) Is the database a container database
      #   storage_type: FS                                     # Database storage to be used. ASM or FS.
      #   oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
      #   oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
      #   redolog_size_in_mb: 100
      #   datafile_dest: /u02/oradata
      #   recoveryfile_dest: /u02/fra
      #   state: present
      #   init_parameters:
      #        - {name: db_create_file_dest, value: '/u02/oradata', scope: both, state: present}
      #        - {name: db_recovery_file_dest, value: '/u02/fra', scope: both, state: present}
      #        - {name: db_recovery_file_dest_size, value: 20G, scope: both, state: present}
      #   services:
      #        - { name: service112,  state: started }
      #   users:
      #     - schema: dbauser
      #       grants:
      #            - dba
      #       state: present
# This will create another database using the same ORACLE_HOME as above (/u10/app/oracle/12.2.0.1/db1, but is not running a listener)
      # - home: db1                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
      #   oracle_version_db: 12.2.0.1                          # Oracle versiono (12.2.0.1,12.1.0.2,12.1.0.1,11.2.0.4,11.2.0.3)
      #   oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
      #   oracle_db_name: blergh                                 # Database name
      #   oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
      #   is_container: false                                # (true/false) Is the database a container database
      #   pdb_prefix: shit
      #   num_pdbs: 0
      #   storage_type: FS                                     # Database storage to be used. ASM or FS.
      #   oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
      #   oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
      #   redolog_size_in_mb: 100
      #   datafile_dest: /u02
      #   recoveryfile_dest: /u02
      #   state: present

# This will create another ORACLE_HOME (/u10/app/oracle/12.1.0.2/db1, a db called xxx but is not running a listener)
      # - home: db1                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
      #   oracle_version_db: 12.1.0.2                          # Oracle versiono (12.2.0.1,12.1.0.2,12.1.0.1,11.2.0.4,11.2.0.3)
      #   oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
      #   oracle_db_name: xxx                                 # Database name
      #   oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
      #   is_container: false                                # (true/false) Is the database a container database
      #   pdb_prefix: pdb
      #   num_pdbs: 0
      #   storage_type: FS                                     # Database storage to be used. ASM or FS.
      #   oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
      #   oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
      #   redolog_size_in_mb: 100
      #   datafile_dest: /u02
      #   recoveryfile_dest: /u02
      #   state: present
