# DB
default_dbpass: Oracle123
dbpasswords:
      orclcdb:
        system: Oracle_123
        sys: Oracle_123
        dbsnmp: Oracle_123
        pdbadmin: Oracle_123
        orclpdb1:
           appuser1: appuser1
