---
# tasks file for orahost-logrotate

- name: Manage logrotate
  template: src=logrotate.j2 dest=/etc/logrotate.d/{{ item.name }}
  with_items:
        - "{{ logrotate_config }}"
  when: logrotate_config is defined
  tags: logrotate

- name: Manage Cleanup-Scripts
  template: src=oracle_cleanup.j2 dest=/etc/cron.daily/oracle_cleanup.sh mode=744
  when: logrotate_config is defined
  tags: cleanup
